### ISSUE TITLE
Few issues

### ISSUE THREAD

**Issue by TbtBI** [realfinder/AVS-Stuff#11]
Hi.

I uploaded [here](https://www.sendspace.com/filegroup/DTXugiKoP92Y9zTa1riEHJoPKC%2BVBSIt) diff for Advanced Denoising.avsi, nnedi3_resize16.avsi and ZS AVS Shared Functions.avsi. Without those changes the scripts aren't working. ZS AVS Shared Functions.avsi has added few helper functions.

**Comment by realfinder** [comment]
thanks

will add them now, but about srmdhae and srmdhai I didn't added them I repced them with spasses(sre,"mt_expand()") and spasses(sre,"mt_inpand()") in dehalo_alpha to reduce duplicate Functions

**Comment by TbtBI** [comment]
There is srmdhae and srmdhai in Masked_DHA.avsi.
There is bh_m4 in BlindDeHalo3_mt2.avsi.

**Comment by realfinder** [comment]
they was forgotten, sorry

fixed them now

**Comment by TbtBI** [comment]
Thanks for the updates.

"," is forgotten in nnedi3_resize16.avsi #540 line - [diff](https://www.sendspace.com/file/yboujy)

**Comment by realfinder** [comment]
done, there are also new things for nnedi3_resize16.avsi

**Comment by TbtBI** [comment]
After the latest nnedi3_resize16.avsi update - line #609 ResizeX doesn't have y, u, v paratemeters.

`shift16  = sischbd || sisprgb ? input16.ResizeX(ow, oh, src_left, src_top, src_width, src_height, kernel="point", luma = y == 3 ? true : false, chroma = u == 3 || v == 3 ? true : false)`

**Comment by realfinder** [comment]
thanks again, fixed

**Comment by TbtBI** [comment]
Thanks.
