### ISSUE TITLE
 ContraSharpen_mod

### ISSUE THREAD

**Issue by TbtBI** [realfinder/AVS-Stuff#114]
Hi,
Can you add [vsMSharpen](https://github.com/Asd-g/AviSynth-vsMSharpen) and [vsTCanny](https://github.com/Asd-g/AviSynth-vsTCanny) in that script?
Thanks.

**Comment by realfinder** [comment]
Hi, I will take some time for vsTCanny since it's kinda not same as TCannyMod and both not same as TCanny

**Comment by TbtBI** [comment]
Sure, take your time.

**Comment by realfinder** [comment]
try eceedf9

**Comment by TbtBI** [comment]
It's ok.
Thanks.
