### ISSUE TITLE
LSFmod error

### ISSUE THREAD

**Issue by kedaitinh12** [realfinder/AVS-Stuff#115]
I meet this error when try index video with lsmashsource

Script error: expected "val", "bool", "int", "float", "string", "array", or "clip" (or their "_array" versions
(C:/Program Files (x86)/AviSynth+/plugins64+/LSFmod_v2.192.avsi, line 422, column 0)

**Comment by realfinder** [comment]
it's fine here, I need more info

**Comment by Sangenshin** [comment]
It also works normally for me

**Comment by kedaitinh12** [comment]
> it's fine here, I need more info
now, it's fine
