### ISSUE TITLE
UTF-8 source files with BOM are not supported by new Zs_RF_Shared.avsi and QTGMC.avsi

### ISSUE THREAD

**Issue by hintlou** [realfinder/AVS-Stuff#137]
I got a warning after I updated the new Zs_RF_Shared.avsi and QTGMC.avsi just now.
”Import: UTF-8 source files with BOM are not supported, re-save script with ANSI or UTF8 w/o BOM encoding! : "C:/Program Files (x86)/AviSynth+/plugins64+/Zs_RF_Shared.avsi"
(F:\so hurt_temp\so hurt_source.avs, line 2)”

**Comment by realfinder** [comment]
it's github issue, I always upload them as ANSI

try resave them as ANSI in notepad

**Comment by hintlou** [comment]
> it's github issue, I always upload them as ANSI
> 
> try resave them as ANSI in notepad

No.
I updated them by copying the words and covering to the old one.
Not download from github.

**Comment by realfinder** [comment]
I did try "save link as" on raw today

![image](https://user-images.githubusercontent.com/2512153/111578100-846ce180-87c4-11eb-9804-f257b7426283.png)

and it show as ANSI in notepad now and work fine even in avs 2.6

so nothing I can do to help you in that case

**Comment by hintlou** [comment]
I retry and it's OK now.Thank you!
