### ISSUE TITLE
Add vsTEdgeMask

### ISSUE THREAD

**Issue by TbtBI** [realfinder/AVS-Stuff#138]
Hi,
Both vsTEdgeMask and TEedgeMask have identical outputs (default parameters).
Can you update ASTDR.avsi and ContraSharpen_mod.avsi for vsTEdgeMask?

**Comment by realfinder** [comment]
sure, it will be done today or in coming days

**Comment by realfinder** [comment]
try them now

**Comment by TbtBI** [comment]
ASTDR.avsi is ok.
[Here](https://github.com/realfinder/AVS-Stuff/blob/Community/avs%202.5%20and%20up/ContraSharpen_mod.avsi#L248) probably threshY should be replaced with prefinal. Now there is no clip supplied to vsTEdgeMask.

**Comment by realfinder** [comment]
prefinal was forgotten...

I just fix it now

**Comment by TbtBI** [comment]
It's ok now.
Thanks.
