### ISSUE TITLE
vsDegrainMedian with HBD

### ISSUE THREAD

**Issue by kedaitinh12** [realfinder/AVS-Stuff#141]
Time to use vsDegrainMedian, hope you update your script with new filter vsDegrainMedian

**Comment by realfinder** [comment]
I did a Quick Search and didn't find any of them use DegrainMedian, if you know ones that use DegrainMedian from the scripts I did update please list them so I can update them to vsDegrainMedian

**Comment by kedaitinh12** [comment]
I don't find out your scripts use it. Sr for disturbed
