### ISSUE TITLE
New MasksPack 2.5

### ISSUE THREAD

**Issue by kedaitinh12** [realfinder/AVS-Stuff#143]
I seen Dogway updated new ver MasksPack, can you still mod new ver MasksPack or delete it on your mod scripts??
Updating MasksPack to v2.5
Removed SatMask (now in GradePack), updated BoxMask and LumaMask: https://github.com/Dogway/Avisynth-Scripts/blob/master/MasksPack.v2.5.avsi

GradePack add Satmask: https://github.com/Dogway/Avisynth-Scripts/blob/master/GradePack.v1.0.avsi

**Comment by realfinder** [comment]
it's better to delete it then, so I did delete it now
