### ISSUE TITLE
FixChromaBleedingMod

### ISSUE THREAD

**Issue by TbtBI** [realfinder/AVS-Stuff#149]
Hi,

The result of 8-bit and 16-bit is different. Test:

```
colorbars(pixel_type="yuv420p16") #colorbars(pixel_type="yv12")
FixChromaBleedingMod(-200)
ExtractV()
```

**Comment by realfinder** [comment]
it's YLevels problem, I did update for it

**Comment by TbtBI** [comment]
Now the results are ok.
I tested it against [this older version](http://avisynth.nl/index.php?title=FixChromaBleedingMod&direction=next&oldid=7116) and the results are different.
```
colorbars(pixel_type="yuv420p8")
FixChromaBleedingMod(-200, xysh=true)
ExtractV()
```

**Comment by realfinder** [comment]
same thing I think, Levels

you can get same as old ouput in avs 2.5, I don't think it's wrong now or anything, just how YLevels work

> Ylevels() is a simple replacement for Avisynth's internal levels() command, with a few neat differences:
> 
> - processes only luma --> faster, better preservation of color saturation
> - no clipping: Ylevels(40,1.0,220, 40, 220) will not clip the output to [40,220] as levels() does. Values below 40 / above 220 will be scaled accordingly to the correct vales. This means, one can use any values for IN_LOW, IN_HIGH as "control points" without getting the input clipped at those values.

**Comment by realfinder** [comment]
but maybe it need some tweaking, I will see about that

**Comment by realfinder** [comment]
see last update of FixChromaBleedingMod

**Comment by TbtBI** [comment]
There are few Levelss calls that should be Levels.

There is obvious difference between 8-bit and 16-bit results.

There is some artifact for 8-bit - https://imgaa.com/image/60e567879884d063673670

**Comment by realfinder** [comment]
the new FixChromaBleedingMod is same as old FixChromaBleedingMod now (at least in 8bit) for me as you asked https://github.com/realfinder/AVS-Stuff/issues/149#issuecomment-873940134 , so what is the problem now?

I don't see much difference in 16 vs 8 bit (and I think it come from something else this time not Levels)

**Comment by realfinder** [comment]
> There are few Levelss calls that should be Levels.

they didn't, https://github.com/raffriff42/AvisynthPlusUtilities/blob/73a0c78692fa4182d5131064b712f373980817f5/Utils-r41.avsi#L2499 seems you didn't read this https://github.com/realfinder/AVS-Stuff/blob/842e04e8905ce1a3206fc59e82c8c5f2a59923f2/avs%202.5%20and%20up/FixChromaBleedingMod.avsi#L2

**Comment by TbtBI** [comment]
My bad, I didn't read about the new requirement.

The latest version is the same as the old version I pointed out. It seems the old version (respectively the last one too) produces some artifacts (https://imgaa.com/image/60e567879884d063673670) - note the small black and white lines of few pixels.
I found [another version](https://gitlab.com/uvz/AviSynthPlus-Plugins-Scripts/-/raw/master/plugins64+/FixChromaBleedingMod_.avsi). Testing with the following code, you can see the artifacts:
```
colorbars(pixel_type="yuv420p8")
FixChromaBleedingMod(-200, xysh=true) #FixChromaBleedingMod(-200) for the other version from gitlab 
ExtractV()

**Comment by realfinder** [comment]
that not bug, it's how original FixChromaBleeding was made, anyway FixChromaBleedingMod(-200, 0, noexpand=true) in last update seems do better in this case

**Comment by TbtBI** [comment]
Yes, it looks better.

Thanks.
