### ISSUE TITLE
Function duplicates with MinBlur from rm_logo_.avsi

### ISSUE THREAD

**Issue by kedaitinh12** [realfinder/AVS-Stuff#151]
"MinBlur" : "C:\Program Files (x86)\AviSynth+\plugins+\rm_logo_.avsi"
"MinBlur" : "C:\Program Files (x86)\AviSynth+\plugins+\Zs_RF_Shared_v1.154.avsi"

**Comment by realfinder** [comment]
don't know about rm_logo_.avsi, maybe you should ask who make it, or just remove MinBlur from rm_logo_.avsi

**Comment by kedaitinh12** [comment]
From here
https://gitlab.com/uvz/AviSynthPlus-Plugins-Scripts/-/blob/master/scripts/rm_logo_.avsi

**Comment by kedaitinh12** [comment]
Btw, frfun7 now is open source
https://github.com/pinterf/Frfun7/

**Comment by kedaitinh12** [comment]
I deleted MinBlur from rm_logo_.avsi
