### ISSUE TITLE
Add BM3D to NotSMDegrain

### ISSUE THREAD

**Issue by kedaitinh12** [realfinder/AVS-Stuff#153]
I think need add BM3D same KNLMeansCL prefilters for quality denoise

**Comment by realfinder** [comment]
NotSMDegrain will not get any update aside from bugs fix https://forum.doom9.org/showpost.php?p=1946141&postcount=751

**Comment by Dogway** [comment]
I personally have nothing against it, real.finder's functions target another user base so both can coexist.

**Comment by realfinder** [comment]
still

btw, from friend that use vs, say that if SMDegrain used as bm3d_basic for BM3D it will be good mixing up, don't know if the opposite case (BM3D as prefilter for SMDegrain) will be that good
