### ISSUE TITLE
F3KDB_3 with stacked input clip not working.

### ISSUE THREAD

**Issue by JulioValc** [realfinder/AVS-Stuff#155]
Line 56 should be:
`noutput_mode==1 ? last.convertbits(16,false).ConvertToStacked() : noutput_mode==2 ? last.convertbits(16,false).ConvertToDoubleWidth() : last`
How it currently is, it will just return the input clip when using stacked input/output.

**Comment by realfinder** [comment]
yes, thanks for report it, fixed
