### ISSUE TITLE
Vinverse_avsi

### ISSUE THREAD

**Issue by TbtBI** [realfinder/AVS-Stuff#159]
Hi, I saw you changed Vinverse_avsi with the latest vinverse in [QTGMC.avsi](https://github.com/realfinder/AVS-Stuff/blob/Community/avs%202.6%20and%20up/QTGMC.avsi). Can you do the same with [AnimeIVTC.avsi](https://github.com/realfinder/AVS-Stuff/blob/Community/avs%202.5%20and%20up/AnimeIVTC.avsi) and [AutoDeblock2.avsi](https://github.com/realfinder/AVS-Stuff/blob/Community/avs%202.5%20and%20up/AutoDeblock2.avsi)?

**Comment by realfinder** [comment]
done [5a0d5b4](https://github.com/realfinder/AVS-Stuff/commit/5a0d5b45fd0a3e502706e4c039ec70f8ba664258)

but there are a down side, the plugin Vinverse don't work with float clip yet

**Comment by TbtBI** [comment]
Noted about float clips.

Thanks for the changes.
