### ISSUE TITLE
sbr and sbrV from Zs_RF_shared same function names with new plugin from Asd-g

### ISSUE THREAD

**Issue by kedaitinh12** [realfinder/AVS-Stuff#160]
Need change name from Zs_RF_shared (maybe)
https://github.com/realfinder/AVS-Stuff/blob/6a90497c96b6e81e15f3ab70cd52de5f782c0736/avs%202.5%20and%20up/Zs_RF_Shared.avsi#L677

**Comment by realfinder** [comment]
is it ok? https://github.com/realfinder/AVS-Stuff/commit/1b002510a980788b6d3458c796a92b3a53a7e56c

**Comment by kedaitinh12** [comment]
Thanks
