### ISSUE TITLE
Error when show=true in LSFM_Show

### ISSUE THREAD

**Issue by kedaitinh12** [realfinder/AVS-Stuff#165]
Error gone when change "int undershoot2" to "float undershoot2"
https://github.com/realfinder/AVS-Stuff/blob/4bf0b83b78bcfbe561cf468c1d9c1714610fd2f9/avs%202.5%20and%20up/LSFmod.avsi#L648

https://github.com/realfinder/AVS-Stuff/blob/4bf0b83b78bcfbe561cf468c1d9c1714610fd2f9/avs%202.5%20and%20up/LSFmod.avsi#L229

**Comment by FranceBB** [comment]
Yep, saw it earlier today on Doom9, I can reproduce this.

**Comment by realfinder** [comment]
it should be fixed now after https://github.com/realfinder/AVS-Stuff/pull/166
