### ISSUE TITLE
Replaced sbr with sbr_avsi in GrainStabilizeMC

### ISSUE THREAD

**Issue by kedaitinh12** [realfinder/AVS-Stuff#172]
Cause sbr plugin doesn't have an r parameter so I think you need to use sbr_avsi to replace sbr
https://github.com/realfinder/AVS-Stuff/blob/e2ac5bf257d3c53c659fa563c73670051c2360d8/avs%202.5%20and%20up/GrainStabilizeMC.avsi#L170

**Comment by realfinder** [comment]
thanks for note it, can you make a pull request?

**Comment by kedaitinh12** [comment]
Ok
https://github.com/realfinder/AVS-Stuff/pull/173
