### ISSUE TITLE
Replace SangNom

### ISSUE THREAD

**Issue by TbtBI** [realfinder/AVS-Stuff#27]
Hi,
why not replace SangNom with SangNom2 in ContraSharpen_mod.avsi and ZS_AVS_Shared_Functions.avsi?

**Comment by realfinder** [comment]
because:-
1- I don't use all these settings!
2- there are some changes may needed not only replace SangNom with SangNom2 (note the order parameter in both)

that why I asked before https://forum.doom9.org/showthread.php?p=1655648#post1655648

**Comment by TbtBI** [comment]
Default order parameter is same for both versions. In those scripts SangNom is used with the default order parameter.

**Comment by realfinder** [comment]
done
