### ISSUE TITLE
DDCOMB

### ISSUE THREAD

**Issue by JySzE** [realfinder/AVS-Stuff#48]
ddcomb is acting very strange, sometimes it actually introduces static dot crawl back or blurs area where there is no dot crawl at all heavily and even takes chunks out of lines, I use it to grab any residual dot crawl that may have been missed. 

Do you think you can add anyway we can further control ddcomb?

**Comment by JySzE** [comment]
Here is an example of dot crawl being added back on the headband symbol and the lines getting chunks taken out:

https://slow.pics/c/QxL8dJlE

Example of blurring: 

https://slow.pics/c/qu1sRo2Q

Look at the scroll on his back, the lines on them are blurred in a very odd way that isnt consistent, 
 
Also I am aware in this examples there is no visible dot crawl in the "DDCOMB Off" example and thats because alot of the other parts of the video does have dot crawl. But this is just an example of how it is damaging the image overall.

**Comment by realfinder** [comment]
there are nothing perfect, but how you use it? can you post your script? better with original video sample

**Comment by JySzE** [comment]
Sure do you have a discord or email? working in github issues is problematic for me.

**Comment by realfinder** [comment]
![image](https://user-images.githubusercontent.com/2512153/80819019-dfadd980-8bdc-11ea-9399-63c03b4c53a6.png)

**Comment by JySzE** [comment]
I was able to fix this, by using masks

**Comment by realfinder** [comment]
can you post the mask code? maybe I will add it to DDComb if it better than this https://forum.doom9.org/showthread.php?p=1910051#post1910051

**Comment by JySzE** [comment]
The mask i used was just a simple mask to avoid smaller lines while grabbing the big ones, but now with the mask its missing shading that has dot crawl. il DM you on discord since its easier for me.
