### ISSUE TITLE
Issues with AnimeIVTC 

### ISSUE THREAD

**Issue by JySzE** [realfinder/AVS-Stuff#50]
With the most updated TIVTC and TDeint:
 
https://github.com/pinterf/TIVTC/releases

Im getting errors "TFMPP: clip2 colorspace must be the same as input clip!"

![image](https://user-images.githubusercontent.com/25883052/81463930-5402f280-9172-11ea-99b0-bb53e93e9dd8.png)

~and "I dont know what "dm" means" - (only happens when using Prefetch() and mode =2)~

^This was srestore getting mad at prefetch

**Comment by JySzE** [comment]
Fixed in 1.0.16

**Comment by realfinder** [comment]
srestore and prefetch should be fixed with https://forum.doom9.org/showthread.php?p=1904672#post1904672 or https://forum.doom9.org/showthread.php?p=1906016#post1906016

using https://github.com/pinterf/GRunT/releases
