### ISSUE TITLE
daa3MOD green lines

### ISSUE THREAD

**Issue by TbtBI** [realfinder/AVS-Stuff#64]
Hi,
```
ffvideosource(1080p)
Crop(0, 138, -0, -138)
daa3mod()
```
has green lines on the bottom - https://images2.imgbox.com/86/e5/yIakeDy3_o.png

**Comment by realfinder** [comment]
it's nnedi3 bug
ColorBars(width=1920, height=1080, pixel_type="yv12")
Crop(0, 138, -0, -138)
PointResize(Width(), 1206)
nnedi3

**Comment by TbtBI** [comment]
Does the nnedi3 author aware of it or does it have to be reported?

**Comment by realfinder** [comment]
can you report it to him please? https://github.com/jpsdr/NNEDI3/issues

**Comment by TbtBI** [comment]
Yes, I will do it.

**Comment by realfinder** [comment]
try daa3mod update
