### ISSUE TITLE
DFMDeRainbow possible bugs,..

### ISSUE THREAD

**Issue by Selur** [realfinder/AVS-Stuff#65]
Not sure if I'm missing something or if there are bugs in
https://github.com/realfinder/AVS-Stuff/blob/Community/avs%202.5%20and%20up/DFMDeRainbow.avsi
1. line 66-68: 
```
themask=subtract(org,YtoUV(first_u,first_v,org)).Levels(108,1,148,0,255)
	\ .svsMSharpen(mask=true,threshold=maskthresh).Invert()
	\ .Blur(0.5).Levels(0,2,255,0,255).Blur(0.5)
```
svsMSharpen should probably be just MSharpen

Also I get 'deen need a YV12 input' when using:
```
LoadCPlugin("I:\Hybrid\32bit\AVISYN~1\ffms2.dll")
LoadPlugin("I:\Hybrid\32bit\AVISYN~1\masktools2.dll")
LoadPlugin("I:\Hybrid\32bit\AVISYN~1\MSharpen.dll")
LoadPlugin("I:\Hybrid\32bit\AVISYN~1\FluxSmooth.dll")
LoadPlugin("I:\Hybrid\32bit\AVISYN~1\Deen.dll")
Import("I:\Hybrid\32bit\avisynthPlugins\Zs_RF_Shared.avsi")
Import("I:\Hybrid\32bit\avisynthPlugins\DFMDeRainbow.avsi")
SetFilterMTMode("DEFAULT_MT_MODE", MT_MULTI_INSTANCE)
FFVideoSource("F:\TESTCL~1\files\test.avi",cachefile="E:\Temp\avi_078c37f69bb356e7b5fa040c71584c40_853323747_1_0.ffindex",fpsnum=25,colorspace="YV12")
DFMDeRainbow(interlaced=false)
return last
```
I use the Deen version from http://ziquash.chez-alice.fr/Deen%20beta%202.zip
is there a newer one which support more than Yv12?

**Comment by realfinder** [comment]
since you used DFMDeRainbow from community branch you need update Zs_RF_Shared.avsi from community branch as well

also make sure you use last minideen (r9), but it has bug when interlaced=true or with field base input anyway

**Comment by Selur** [comment]
Thanks that worked fine!
You might want to adjust the script from
```
# Required plugins:
# MSharpen, MaskTools, FluxSmooth, Deen
```
to
```
# Required plugins:
# MSharpen, MaskTools, FluxSmooth, neo-miniDeen
```

Thanks!

**Comment by realfinder** [comment]
well, if you use it with 2.5, then Deen will be needed
