### ISSUE TITLE
QTGMC potential typo

### ISSUE THREAD

**Issue by missuse** [realfinder/AVS-Stuff#66]
Hi,

Thank you for you effort, it is much appreciated.

On line 601 of [`QTGMC.avsi`](https://github.com/realfinder/AVS-Stuff/blob/Community/avs%202.6%20and%20up/QTGMC.avsi#L601)

I trust 
`V==ChromaNoise?3:2`

should be changed to

`V=ChromaNoise?3:2`

All the best,

Milan

**Comment by realfinder** [comment]
thanks for report, will fix it now
