### ISSUE TITLE
LSFmod.avsi and Smethod=5

### ISSUE THREAD

**Issue by BlohoJo** [realfinder/AVS-Stuff#92]
At some point in [LSFmod.avsi](https://github.com/realfinder/AVS-Stuff/blob/Community/avs%202.5%20and%20up/LSFmod.avsi), Smethod=5 was removed:
```
477  Assert( ( Smethod >= 1 && Smethod <= 4 ) ? true : false, chr(10) + "'Smethod' have not a correct value! [1,2,3,4]" + chr(10))
```

According to the [AviSynth Wiki](http://avisynth.nl/index.php/LSFmod#Syntax_and_Parameters), these should be the values for Smethod:

```
int Smethod = 2

    Sharpening method: (not used for Smode=1&2)

        1 : 3x3 Kernel
        2 : Min/Max (original)
        3 : Min/Max (enhanced)
        4 : Min/Max (original) + 3x3 Kernel
        5 : Min/Max (enhanced) + 3x3 Kernel 
```

Are these Smethods still the same? Is it correct that Smethod=5 should be removed?

**Comment by realfinder** [comment]
> 
> 
> At some point in [LSFmod.avsi](https://github.com/realfinder/AVS-Stuff/blob/Community/avs%202.5%20and%20up/LSFmod.avsi), Smethod=5 was removed:
> 
> ```
> 477  Assert( ( Smethod >= 1 && Smethod <= 4 ) ? true : false, chr(10) + "'Smethod' have not a correct value! [1,2,3,4]" + chr(10))
> ```
> 

it's same as http://latoninf.free.fr/d9/LM/LSFmod.v1.9.avsi so I have no answer to that, the one who know is LaTo the original author

**Comment by BlohoJo** [comment]
Thanks for the fast reply! :)

I'll see if [anyone on Doom9 knows](https://forum.doom9.org/showthread.php?p=1919333#post1919333). ;)
