### ISSUE TITLE
StabilizationToolsPack.avsi and Zs_RF_Shared_v1.139.avsi have function duplicates 

### ISSUE THREAD

**Issue by kedaitinh12** [realfinder/AVS-Stuff#96]
I checked with avs info tool and meet this error:

[Plugin errors/warnings]
____________________________________________________________________________________________________________

Function duplicates:

"FillBorders" : "[PluginFunction]"
"FillBorders" : "C:\Program Files (x86)\AviSynth+\plugins64+\Stabilization_Tools_Pack_v2.1mod2.51.avsi"
"undefined" : "[InternalFunction]"
"Undefined" : "C:\Program Files (x86)\AviSynth+\plugins64+\Zs_RF_Shared_v1.139.avsi"

**Comment by Selur** [comment]
Looking at https://github.com/realfinder/AVS-Stuff/blob/Community/avs%202.5%20and%20up/Zs_RF_Shared.avsi I can't see 'FillBorders' in Zs_RF_Shared.avsi , are you sure you use the latest version?

**Comment by kedaitinh12** [comment]
> Looking at https://github.com/realfinder/AVS-Stuff/blob/Community/avs%202.5%20and%20up/Zs_RF_Shared.avsi I can't see 'FillBorders' in Zs_RF_Shared.avsi , are you sure you use the latest version?

Please read slowly, fillborders function from Stabilization_Tools_Pack

**Comment by Selur** [comment]
Yes, I see the FillBorders function in https://github.com/realfinder/AVS-Stuff/blob/Community/avs%202.5%20and%20up/StabilizationToolsPack.avsi but to have duplicates there needs to be another function with that name somewhere and according to what you posted is sounded to me like this one should be in Zs_RF_Shared_v1.139.avsi which is not the case with the latest git version,... may be I just misunderstood your initial post,...

**Comment by kedaitinh12** [comment]
> Yes, I see the FillBorders function in https://github.com/realfinder/AVS-Stuff/blob/Community/avs%202.5%20and%20up/StabilizationToolsPack.avsi but to have duplicates there needs to be another function with that name somewhere and according to what you posted is sounded to me like this one should be in Zs_RF_Shared_v1.139.avsi which is not the case with the latest git version,... may be I just misunderstood your initial post,...

This function same name with fillborders.dll filter

**Comment by Selur** [comment]
ahh,... okay, i guess changing the function name in StabilizationToolsPack should be easily done. :)

**Comment by realfinder** [comment]
StabilizationToolsPack: well, since dogway is back I think we should ask him first @Dogway

Zs_RF_Shared: it's not problem https://forum.doom9.org/showthread.php?p=1920733#post1920733

**Comment by realfinder** [comment]
try https://github.com/realfinder/AVS-Stuff/blob/Community/avs%202.5%20and%20up/StabilizationToolsPack.avsi

**Comment by kedaitinh12** [comment]
> try https://github.com/realfinder/AVS-Stuff/blob/Community/avs%202.5%20and%20up/StabilizationToolsPack.avsi

thanks
